/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.CartItemDto = factory(root.SzarchHziApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CartItemDto model module.
   * @module model/CartItemDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CartItemDto</code>.
   * @alias module:model/CartItemDto
   * @class
   * @param menuItemId {String} 
   * @param amount {Number} 
   */
  var exports = function(menuItemId, amount) {
    var _this = this;

    _this['menuItemId'] = menuItemId;
    _this['amount'] = amount;
  };

  /**
   * Constructs a <code>CartItemDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CartItemDto} obj Optional instance to populate.
   * @return {module:model/CartItemDto} The populated <code>CartItemDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('menuItemId')) {
        obj['menuItemId'] = ApiClient.convertToType(data['menuItemId'], 'String');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} menuItemId
   */
  exports.prototype['menuItemId'] = undefined;
  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;



  return exports;
}));


