/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.ClientDto = factory(root.SzarchHziApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ClientDto model module.
   * @module model/ClientDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ClientDto</code>.
   * @alias module:model/ClientDto
   * @class
   * @param email {String} 
   * @param name {String} 
   * @param address {String} 
   * @param loyaltyPoints {Number} 
   */
  var exports = function(email, name, address, loyaltyPoints) {
    var _this = this;

    _this['email'] = email;
    _this['name'] = name;
    _this['address'] = address;

    _this['loyaltyPoints'] = loyaltyPoints;
  };

  /**
   * Constructs a <code>ClientDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ClientDto} obj Optional instance to populate.
   * @return {module:model/ClientDto} The populated <code>ClientDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('loyaltyPoints')) {
        obj['loyaltyPoints'] = ApiClient.convertToType(data['loyaltyPoints'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {Number} loyaltyPoints
   */
  exports.prototype['loyaltyPoints'] = undefined;



  return exports;
}));


