/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CartItemDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CartItemDto'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.OrderRequestDto = factory(root.SzarchHziApi.ApiClient, root.SzarchHziApi.CartItemDto);
  }
}(this, function(ApiClient, CartItemDto) {
  'use strict';




  /**
   * The OrderRequestDto model module.
   * @module model/OrderRequestDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderRequestDto</code>.
   * @alias module:model/OrderRequestDto
   * @class
   * @param cart {Array.<module:model/CartItemDto>} 
   * @param discount {Number} 
   */
  var exports = function(cart, discount) {
    var _this = this;

    _this['cart'] = cart;
    _this['discount'] = discount;
  };

  /**
   * Constructs a <code>OrderRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderRequestDto} obj Optional instance to populate.
   * @return {module:model/OrderRequestDto} The populated <code>OrderRequestDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cart')) {
        obj['cart'] = ApiClient.convertToType(data['cart'], [CartItemDto]);
      }
      if (data.hasOwnProperty('discount')) {
        obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CartItemDto>} cart
   */
  exports.prototype['cart'] = undefined;
  /**
   * @member {Number} discount
   */
  exports.prototype['discount'] = undefined;



  return exports;
}));


