/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CartItemDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CartItemDto'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.OrderDto = factory(root.SzarchHziApi.ApiClient, root.SzarchHziApi.CartItemDto);
  }
}(this, function(ApiClient, CartItemDto) {
  'use strict';




  /**
   * The OrderDto model module.
   * @module model/OrderDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>OrderDto</code>.
   * @alias module:model/OrderDto
   * @class
   * @param orderId {String} 
   * @param orderItems {Array.<module:model/CartItemDto>} 
   */
  var exports = function(orderId, orderItems) {
    var _this = this;

    _this['orderId'] = orderId;
    _this['orderItems'] = orderItems;










  };

  /**
   * Constructs a <code>OrderDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderDto} obj Optional instance to populate.
   * @return {module:model/OrderDto} The populated <code>OrderDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
      }
      if (data.hasOwnProperty('orderItems')) {
        obj['orderItems'] = ApiClient.convertToType(data['orderItems'], [CartItemDto]);
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Date');
      }
      if (data.hasOwnProperty('sum')) {
        obj['sum'] = ApiClient.convertToType(data['sum'], 'Number');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('tableId')) {
        obj['tableId'] = ApiClient.convertToType(data['tableId'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('ownerId')) {
        obj['ownerId'] = ApiClient.convertToType(data['ownerId'], 'String');
      }
      if (data.hasOwnProperty('ownerName')) {
        obj['ownerName'] = ApiClient.convertToType(data['ownerName'], 'String');
      }
      if (data.hasOwnProperty('address')) {
        obj['address'] = ApiClient.convertToType(data['address'], 'String');
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
      }
      if (data.hasOwnProperty('discount')) {
        obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {Array.<module:model/CartItemDto>} orderItems
   */
  exports.prototype['orderItems'] = undefined;
  /**
   * @member {Date} time
   */
  exports.prototype['time'] = undefined;
  /**
   * @member {Number} sum
   */
  exports.prototype['sum'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} tableId
   */
  exports.prototype['tableId'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} ownerId
   */
  exports.prototype['ownerId'] = undefined;
  /**
   * @member {String} ownerName
   */
  exports.prototype['ownerName'] = undefined;
  /**
   * @member {String} address
   */
  exports.prototype['address'] = undefined;
  /**
   * @member {Number} rating
   */
  exports.prototype['rating'] = undefined;
  /**
   * @member {Number} discount
   */
  exports.prototype['discount'] = undefined;



  return exports;
}));


