/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.RatingDto = factory(root.SzarchHziApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RatingDto model module.
   * @module model/RatingDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>RatingDto</code>.
   * @alias module:model/RatingDto
   * @class
   * @param orderId {String} 
   * @param rating {Number} 
   */
  var exports = function(orderId, rating) {
    var _this = this;

    _this['orderId'] = orderId;
    _this['rating'] = rating;
  };

  /**
   * Constructs a <code>RatingDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RatingDto} obj Optional instance to populate.
   * @return {module:model/RatingDto} The populated <code>RatingDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('orderId')) {
        obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} orderId
   */
  exports.prototype['orderId'] = undefined;
  /**
   * @member {Number} rating
   */
  exports.prototype['rating'] = undefined;



  return exports;
}));


