/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.ReservationDto = factory(root.SzarchHziApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ReservationDto model module.
   * @module model/ReservationDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReservationDto</code>.
   * @alias module:model/ReservationDto
   * @class
   * @param tableId {String} 
   * @param time {Date} 
   * @param duration {Number} 
   * @param personNumber {Number} 
   */
  var exports = function(tableId, time, duration, personNumber) {
    var _this = this;

    _this['tableId'] = tableId;
    _this['time'] = time;
    _this['duration'] = duration;


    _this['personNumber'] = personNumber;


  };

  /**
   * Constructs a <code>ReservationDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservationDto} obj Optional instance to populate.
   * @return {module:model/ReservationDto} The populated <code>ReservationDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tableId')) {
        obj['tableId'] = ApiClient.convertToType(data['tableId'], 'String');
      }
      if (data.hasOwnProperty('time')) {
        obj['time'] = ApiClient.convertToType(data['time'], 'Date');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
      if (data.hasOwnProperty('reservationId')) {
        obj['reservationId'] = ApiClient.convertToType(data['reservationId'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('personNumber')) {
        obj['personNumber'] = ApiClient.convertToType(data['personNumber'], 'Number');
      }
      if (data.hasOwnProperty('clientId')) {
        obj['clientId'] = ApiClient.convertToType(data['clientId'], 'String');
      }
      if (data.hasOwnProperty('waiterId')) {
        obj['waiterId'] = ApiClient.convertToType(data['waiterId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} tableId
   */
  exports.prototype['tableId'] = undefined;
  /**
   * @member {Date} time
   */
  exports.prototype['time'] = undefined;
  /**
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;
  /**
   * @member {String} reservationId
   */
  exports.prototype['reservationId'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Number} personNumber
   */
  exports.prototype['personNumber'] = undefined;
  /**
   * @member {String} clientId
   */
  exports.prototype['clientId'] = undefined;
  /**
   * @member {String} waiterId
   */
  exports.prototype['waiterId'] = undefined;



  return exports;
}));


