/**
 * Szarch Házi API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SzarchHziApi) {
      root.SzarchHziApi = {};
    }
    root.SzarchHziApi.TableDto = factory(root.SzarchHziApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The TableDto model module.
   * @module model/TableDto
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TableDto</code>.
   * @alias module:model/TableDto
   * @class
   * @param tableId {String} 
   * @param seats {Number} 
   */
  var exports = function(tableId, seats) {
    var _this = this;

    _this['tableId'] = tableId;
    _this['seats'] = seats;
  };

  /**
   * Constructs a <code>TableDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TableDto} obj Optional instance to populate.
   * @return {module:model/TableDto} The populated <code>TableDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tableId')) {
        obj['tableId'] = ApiClient.convertToType(data['tableId'], 'String');
      }
      if (data.hasOwnProperty('seats')) {
        obj['seats'] = ApiClient.convertToType(data['seats'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} tableId
   */
  exports.prototype['tableId'] = undefined;
  /**
   * @member {Number} seats
   */
  exports.prototype['seats'] = undefined;



  return exports;
}));


